### PR TITLE
fix: fix a bug where server would crash when node was used in a subflow and user tried to upload a file

### LINKED ISSUE #9: Using this node in a subflow crashes the node-red server
I've tried adding this node to a subflow and every time I do, once I click the upload button it crashes the server. Here is an example of the subflow I am using (but it should be reproducible any time you use it in a subflow):
```json
[
    {
        "id": "ab143ae234639771",
        "type": "subflow",
        "name": "Subflow 5",
        "info": "",
        "in": [
            {
                "x": 60,
                "y": 80,
                "wires": [
                    {
                        "id": "4191a6f96fbbdef6"
                    }
                ]
            }
        ],
        "out": [
            {
                "x": 780,
                "y": 80,
                "wires": [
                    {
                        "id": "f6138561e5ba2cc8",
                        "port": 0
                    }
                ]
            }
        ]
    },
    {
        "id": "4191a6f96fbbdef6",
        "type": "ui_upload",
        "z": "ab143ae234639771",
        "group": "06fcee6ae387d692",
        "title": "upload",
        "name": "",
        "order": 3,
        "width": 0,
        "height": 5,
        "chunk": 256,
        "transfer": "binary",
        "x": 190,
        "y": 80,
        "wires": [
            [
                "c04ecb54869f1234"
            ]
        ]
    },
    {
        "id": "f6138561e5ba2cc8",
        "type": "function",
        "z": "ab143ae234639771",
        "name": "Allow access to certificate globally",
        "func": "global.set('certificate', msg.payload);\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 560,
        "y": 80,
        "wires": [
            []
        ]
    },
    {
        "id": "c04ecb54869f1234",
        "type": "json",
        "z": "ab143ae234639771",
        "name": "",
        "property": "payload",
        "action": "",
        "pretty": false,
        "x": 330,
        "y": 80,
        "wires": [
            [
                "f6138561e5ba2cc8"
            ]
        ]
    },
    {
        "id": "06fcee6ae387d692",
        "type": "ui_group",
        "name": "API input",
        "tab": "998ca7fbf9a4874e",
        "order": 1,
        "disp": true,
        "width": "10",
        "collapse": false,
        "className": ""
    },
    {
        "id": "998ca7fbf9a4874e",
        "type": "ui_tab",
        "name": "API input",
        "icon": "dashboard",
        "disabled": false,
        "hidden": false
    },
    {
        "id": "9a9cca779db28544",
        "type": "subflow:ab143ae234639771",
        "z": "2a80dbf55bb7c970",
        "x": 680,
        "y": 280,
        "wires": [
            [
                "5af85ebf24ddfbf2"
            ]
        ]
    }
]
```

Here is the error that I get when it crashes:
```javascript
19 May 10:24:48 - [error] TypeError: Cannot read properties of undefined (reading 'id')
    at /Users/eamon/work/node-red-api-flow/node_modules/node-red-contrib-ui-upload/ui_upload.js:341:74
    at findOutputNodeId (/Users/eamon/work/node-red-api-flow/node_modules/node-red-contrib-ui-upload/ui_upload.js:288:20)
    at Object.beforeSend (/Users/eamon/work/node-red-api-flow/node_modules/node-red-contrib-ui-upload/ui_upload.js:341:26)
    at EventEmitter.handler (/Users/eamon/work/node-red-api-flow/node_modules/node-red-dashboard/ui.js:288:22)
    at EventEmitter.emit (node:events:538:35)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/Users/eamon/work/node-red-api-flow/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/eamon/work/node-red-api-flow/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

I using Mac OS version 12.3.1, here are the versions of the nodes and node-red:
```json
		"node-red": "^2.2.2",
		"node-red-contrib-ui-upload": "~0.5.1",
		"node-red-dashboard": "~3.1.7"
```

It works perfectly for me when used normally, but as soon as I use it in a subflow and try to upload something it crashes.

### PR DESCRIPTION
**Pull request by eamon0989**
When attempting to use this node in a subflow and clicking the upload button in the UI, the node-red server would crash. This PR fixes that issue.

Fixes #9

### CODE REVIEW

**Comment by Alkarex** [comment]
I have fixed with a slightly different approach https://github.com/alexandrainst/node-red-contrib-ui-upload/pull/10/commits/39021025f7dd628f2eb5f141cb418f364e7b3901
Could you please pull and test again?

**Comment by eamon0989** [comment]
I've just tested your approach and it appears to work perfectly, thanks very much!

**Comment by Alkarex** [comment]
Sorry, I was visibly not enough awake, and the test was on the wrong variable. Could you please test one more time? 🙈

**Comment by eamon0989** [comment]
Haha, no problem. Tested, and it appears to be working as expected :-) 👍🏼

**Comment by Alkarex** [comment]
Thanks! I will make a release tonight

**Comment by Alkarex** [comment]
https://github.com/alexandrainst/node-red-contrib-ui-upload/releases/tag/v0.5.2

**Pull request merged**
